controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - blockfl_to_fl

velocity_controller:
  ros__parameters:
    joints:
      - blockfl_to_fl